config/routes.rb
StopfinderDev::Application.routes.draw do
 # devise_for :users

  root :to => 'about#main'
  
  resources :busstops
  resources :closures
  resources :contact_forms
  resources :sresponses
  #resources :authorizations
  
  get '/update/:id' => 'busstops#update', :as => :submitinfo
  get '/edit/:id' => 'busstops#edit', :as => :duplicateentry
  get '/add/:id' => 'busstops#addnew'
  get '/closed/:id' => 'closures#report'
  get '/profile' => 'reputation#profile', :as => :userprofile
  get '/user/:id' => 'reputation#publicprofile'
  get '/topcontributors' => 'reputation#top'
  get '/badges' => 'reputation#badges'
  get '/confirm' => 'reputation#confirmdelete'
  get '/delete' => 'reputation#delete', :as => :deleteaccount
  get '/about/faq' => 'about#faq'
  get '/find' => 'about#find'
  get '/usernotfound' => 'reputation#usernotfound', :as => :missinguser
  get '/survey/' => 'sresponses#surveyform', :as => :takesurvey
  match 'about/entry/:id' => 'about#entry', :as => :dataentry
  match 'about/survey/submitted'  => 'about#survey', :as => :surveyresponse
  match 'about/contact/:id' => 'about#contact', :as => :emailentry
  match 'about/deleted' => 'about#deleted', :as => :accountdeleted
  match '/testing' => 'about#testing'
  match '/busstops/:id' => 'busstops#show', :as => :dataview
  
  # Routing for info/tutorials
  get '/about/fields' => 'about#data'
  get '/about/missing' => 'about#missing'
  
  # Routing for login
  get   '/login', :to => 'sessions#new', :as => :login
  get   '/logout', :to => 'sessions#destroy', :as => :logout
  #get	'/manage/account', :to => 'sessions#edit', as => :manage
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

  #Routing for reputation/profile
  post '/profile' => 'reputation#create'
  post 'about/main' => 'about#create'
  
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/closure.rb
class Closure < ActiveRecord::Base
  self.table_name = "closures"
  attr_accessible :UserId, :AgencyId, :StopId, :UserIP, :UserAtStop, :DateCreated, 
    :ClosureType, :ClosurePermanent, :StartDate, :EndDate, :MovedTo
    
    
  def self.closureStatus(allReports)
    dateReported = Time.new(2000)
      
    if (allReports.any? == false)
      return ["open"]
    end
    
    status = allReports[0].ClosureType
    if (status == "open")
      return ["open"]
    else
      # Current or future closure report
      dateReported = allReports[0].StartDate
      
      allReports.each do |report|
        if (report.ClosurePermanent == "no" && report.ClosureType != "open")
          return ["closed", dateReported.strftime("%B %d, %Y"), report.EndDate.strftime("%B %d, %Y at %I:%M %p")]
        end
      end
    end
    
    # If we haven't otherwise returned, no end date
    return ["closed", dateReported.strftime("%B %d, %Y"), "none"]
  end
  
  
end

app/controllers/closures_controller.rb
class ClosuresController < ApplicationController
 
  def report
    ids = (params[:id]).split(/[_?=&]/)
    agencyid = ids[0]
    stopid = ids[1]
    @busstop = BusStop.find_by_sql("SELECT * FROM " + BusStop.table_name + " WHERE stopid = " + stopid + " AND agencyid = " + agencyid)[0]
    
    showLog = BusStop.usageLogger
    showLog.info("Viewing closure report form for #{agencyid}_#{stopid} at #{Time.now}")
    
    if(!session[:device_id].blank?)
      showLog.info("Accessed by user #{session[:device_id]}")
    end

    if(!cookies[:user_email].blank?)
      showLog.info("User logged in as #{cookies[:user_email]}")
    end
    
    showLog.info("")
  end
  
  def create
    @report = Closure.new(params[:closure])
    
    # If the closure is permanent or unknown, enddate is infinity (a year from now)
    if (@report.ClosureType == "open")
      @report.EndDate = Time.now + 31560000      
      @report.StartDate = Time.now
    elsif (@report.ClosureType == "current")
      @report.StartDate = Time.now
    elsif (@report.ClosureType == "future")
      #@report.StartDate = @report.StartDate.in_time_zone("")
    end
    
    if (@report.ClosurePermanent == "no")
      #@report.EndDate = @report.EndDate.utc
    else
      @report.EndDate = Time.now + 31560000
    end
    
    @report.save
    
    showLog = BusStop.usageLogger
    showLog.info("Submitted closure report form for #{params[:closure][:AgencyId]}_#{params[:closure][:StopId]} at #{Time.now}")
    
    if(!session[:device_id].blank?)
      showLog.info("Submitted by user #{session[:device_id]}")
    end

    if(!cookies[:user_email].blank?)
      showLog.info("User logged in as #{cookies[:user_email]}")
    end
    
    showLog.info("")
    
    redirect_to dataentry_url(:id => params[:closure][:AgencyId] + "_" + params[:closure][:StopId])
  end
  
end

app/views/closures/report.erb
<div style="padding:5px;">
<table>
<tr><td colspan=2>

<h2><%= session[:stop_name] %></h2>

</td></tr>
<%= form_for :closure, url: closures_path do |f| %>
<tr><td colspan=2>Is the stop closed or open?</td></tr>
<tr>
  <td colspan=2>
    <%= f.radio_button :ClosureType, "open", :checked => true %> Open.
  </td>
</tr>
<tr>
  <td colspan=2>
    <%= f.radio_button :ClosureType, "current" %> Currently closed.
  </td>
</tr>
<tr>
  <td colspan=2>
    <%= f.radio_button :ClosureType, "future" %> Closed starting at: <br/>
    <%= f.datetime_select :StartDate, :default => Time.now  %>
  </td>
</tr>

<tr><td colspan=2 height=20></td></tr>
<tr><td colspan=2>If closed, how long is it closed for?</td></tr>

<tr>
  <td colspan=2>
    <%= f.radio_button :ClosurePermanent, "unknown", id: 'permanent_closed', :checked => true %> Unknown.
  </td>
</tr>
<tr>
  <td colspan=2>
    <%= f.radio_button :ClosurePermanent, "yes", id: 'permanent_closed' %> Stop is closed permanently.
  </td>
</tr>
<tr>
  <td colspan=2>
    <%= f.radio_button :ClosurePermanent, "no", id: 'permanent_closed' %> Stop is closed until: <br />
    <%= f.datetime_select :EndDate, :default => (Time.now).advance(:hours => 1) %>
  </td>
</tr>

<tr><td colspan=2 height=20></td></tr>
<tr><td colspan=2>Is there a suggested alternate stop?</td></tr>

<tr>
  <td colspan=2>
    <%= f.text_area :MovedTo, :value =>"", :rows =>3, :cols =>20 %>
  </td>
</tr>
</table>

<%= f.hidden_field :UserId, :value => cookies[:user_email] %>
<%= f.hidden_field :StopId, :value => @busstop.StopId %>
<%= f.hidden_field :AgencyId, :value => @busstop.AgencyId %>
<%= f.hidden_field :DateCreated, :value => Time.now %>

<%= f.label :at_stop do %>
  <%= f.check_box :UserAtStop %> I am currently at this stop.
<% end %>
  
<p>
  <%= f.submit "Report closure" %>
</p>
<% end %>

</div>